name: EAS Build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Expo App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Log in to EAS
        run: eas login --token ${{ secrets.EAS_TOKEN }}

      - name: Start EAS Build
        run: eas build --platform all --profile production --non-interactive
